async function ai_edge_gallery_get_result(inputJson) {
  const input = JSON.parse(inputJson);
  const title = input.title || "Report";
  // Accept "items" array or collect all non-title values as items.
  let items = input.items;
  if (!items || !Array.isArray(items)) {
    const collected = Object.entries(input)
      .filter(([k]) => k !== 'title')
      .map(([k, v]) => String(v));
    items = collected.length > 0 ? collected : ["No data provided"];
  }
  const itemsHtml = items.map(item => `<li>${item}</li>`).join('\n');
  const html = `
    <div style="font-family:sans-serif;max-width:400px;margin:0 auto;padding:16px;border:1px solid #ddd;border-radius:12px;background:#f9f9f9">
      <h2 style="color:#1a73e8;margin:0 0 12px">${title}</h2>
      <ul style="padding-left:20px;margin:0">${itemsHtml}</ul>
      <p style="color:#666;font-size:12px;margin:12px 0 0">Generated by format-report skill</p>
    </div>`;
  return JSON.stringify({
    webview: { url: null, iframe: false, aspectRatio: 0.8 },
    result: html
  });
}
