  name: Build Android APK
  
  on:
    workflow_dispatch:
    push:
      branches: [ "main" ]
      paths:
        - 'Android/**'
    pull_request:
      branches: [ "main" ]
      paths:
        - 'Android/**'
  
  jobs:
    build_apk:
      name: Build Android APK
      runs-on: ubuntu-latest
      permissions:
        contents: read
      defaults:
        run:
          working-directory: ./Android/src
      steps:
        - name: Checkout the source code
          uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
          with:
            persist-credentials: false
        - uses: actions/setup-java@cf277c60eb25467037889841efdb72551f06f6c3 # v4
          with:
            distribution: 'temurin'
            java-version: '21'
        - name: Install Android SDK Platform 37
          run: echo "y" | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "platforms;android-37.0"
        - name: Build
          run: ./gradlew assembleRelease
  
  
