  name: Build Android APK
  
  on:
    workflow_dispatch:
    push:
      branches: [ "main" ]
      paths:
        - 'Android/**'
    pull_request:
      branches: [ "main" ]
      paths:
        - 'Android/**'
  
  jobs:
    build_apk:
      name: Build Android APK
      runs-on: ubuntu-latest
      permissions:
        contents: read
      defaults:
        run:
          working-directory: ./Android/src
      steps:
        - name: Checkout the source code
          uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3
          with:
            persist-credentials: false
        - uses: actions/setup-java@d7793b545071e98d581d3bf084a51c3213318a07 # v4
          with:
            distribution: 'temurin'
            java-version: '21'
        - name: Install Android SDK Platform 37
          run: echo "y" | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "platforms;android-37.0"
        - name: Build
          run: ./gradlew assembleRelease
  
  
